name: circom_witnesscalc_example
description: "Demonstrates how to use the circom_witnesscalc plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_rapidsnark: ^0.0.1-alpha.3
  circom_witnesscalc:
    path: ../

  cupertino_icons: ^1.0.8

  share_plus: ^10.1.2
  file_picker: ^8.1.4
  path_provider: ^2.1.3


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/authV2.wcd
    - assets/authV2_inputs.json
    - assets/authV2.zkey
    - assets/authV2_verification_key.json
